name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x8r4y7j7

      - name: Build Docker image
        run: docker build -t lambda-forge ecr/.

      - name: Tag Docker image
        run: docker tag lambda-forge:latest public.ecr.aws/x8r4y7j7/lambda-forge:latest

      - name: Push Docker image to ECR
        run: docker push public.ecr.aws/x8r4y7j7/lambda-forge:latest

  deploy-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material 

      - name: Deploy to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: | 
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git config --global user.email "guialvespimenta27@gmail.com"
          git config --global user.name "Guilherme Alves Pimenta"
          mkdocs gh-deploy --remote-name origin --remote-branch gh-pages --force --config-file docs/mkdocs.yml
